name: frontend
description: "Catalystic Wanders App - Connecting communities through travel and cultural exchange"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.8.1

  # State management
  provider: ^6.1.2

  # 3D model viewer
  model_viewer_plus: ^1.9.3

  # Audio playback
  audioplayers: ^6.5.1

  # HTTP and networking
  dio: ^5.9.0

  # Caching / images
  cached_network_image: ^3.4.1

  # Routing
  go_router: ^12.1.3

  # Platform & storage
  shared_preferences: ^2.2.3
  intl: ^0.20.2

  # Maps
  google_maps_flutter: ^2.10.1

  # Web plugin glue (safe to keep, does nothing on mobile)
  flutter_web_plugins:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  test: ^1.24.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/videos/hologram.mp4
    - assets/models/
    - assets/models/ZuluHat.glb
    - assets/audio/
  #   - assets/images/backgrounds/
  #   - assets/images/icons/
  #   - assets/images/products/
  #   - assets/images/destinations/
  #   - assets/images/experiences/
  #   - assets/data/
  #   - assets/fonts/

  # fonts:
  #   - family: Ubuntu
  #     fonts:
  #       - asset: assets/fonts/Ubuntu-Regular.ttf
  #       - asset: assets/fonts/Ubuntu-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Ubuntu-Light.ttf
  #         weight: 300
