name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  provider: ^6.1.5+1
  cached_network_image: ^3.4.1
  go_router: ^16.2.1
  google_maps_flutter: ^2.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
